#pragma once
enum CHESS_COLUMN { C_A = 0, C_B, C_C, C_D, C_E, C_F, C_G, C_H };
enum CHESS_ROW { R_1 = 0, R_2, R_3, R_4, R_5, R_6, R_7, R_8 };
enum PLAYER_COLOR { WHITE, BLACK };
enum CHESS_PIECES { PAWN, KNIGHT, TOWER, BISHOP, QUEEN, KING };
enum CHESS_GAME_STATE { WINNER_BLACK, WINNER_WHITE, STALEMATE, CONTINIUE };